service: svlesstemplate

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    LOG_LEVEL: ${env:LOG_LEVEL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}" 

functions:
  saveData:
    handler: dist/handlers/dataSaveHandler.saveDataHandler
    events:
      - http:
          path: /data
          method: post
          cors: true
  fetchData:
    handler: dist/handlers/dataFetchHandler.fetchDataHandler
    events:
      - http:
          path: /data
          method: get
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  
package:
  individually: true
  patterns:
    - '!**/*'
    - 'dist/**'  
    - 'node_modules/**'

custom:
  dotenv:
    path: .env

resources:
  Resources:
    # Add any additional resources here if needed
